pipeline:
  identifier: Build_Miecznikk_GraphicsApp_1724083006261
  name: Build GraphicsApp
  orgIdentifier: default
  projectIdentifier: Default_Project
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1724082727901
                    repoName: Miecznikk/GraphicsApp
                    build:
                      type: branch
                      spec:
                        branch: main
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1724082727901
        repoName: Miecznik/GraphicsApp
        build: <+input>
